language: python

#Python Version
python:

  - "3.7"

# Install dependencies and libraries 
install:

  - pip install -r requirements.txt

# command to run tests

deploy:
  provider: heroku
  api_key: 00ee7257-5e8c-408e-bc03-7bacef4bc45d
  app: app