language: python

#Python Version
python:

  - "3.7"

# Install dependencies and libraries 
install:

  - pip install -r requirements.txt

deploy:
  provider: heroku
  api_key:
    secure: 474318ef-2c76-42fd-8cf8-20e5a6dcde5a
  app: link-my-bio-fer
  on:
    repo: Fernando0107/https://github.com/Fernando0107/linkmybio